# TCL File Generated by Component Editor 21.1
# Wed May 14 03:16:25 EDT 2025
# DO NOT MODIFY


# 
# nbody "NBody Sim" v1.0
#  2025.05.14.03:16:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module nbody
# 
set_module_property DESCRIPTION ""
set_module_property NAME nbody
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "NBody Sim"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_assignment embeddedsw.dts.vendor "Isaac"
set_module_assignment embeddedsw.dts.name "nbody"
set_module_assignment embeddedsw.dts.group "sim"



# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nbody
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file nbody.sv SYSTEM_VERILOG PATH nbody.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BODIES INTEGER 512
set_parameter_property BODIES DEFAULT_VALUE 512
set_parameter_property BODIES DISPLAY_NAME BODIES
set_parameter_property BODIES TYPE INTEGER
set_parameter_property BODIES UNITS None
set_parameter_property BODIES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BODIES HDL_PARAMETER true
add_parameter EXT_DATA_WIDTH INTEGER 32
set_parameter_property EXT_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property EXT_DATA_WIDTH DISPLAY_NAME EXT_DATA_WIDTH
set_parameter_property EXT_DATA_WIDTH TYPE INTEGER
set_parameter_property EXT_DATA_WIDTH UNITS None
set_parameter_property EXT_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property EXT_DATA_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 64
set_parameter_property DATA_WIDTH DEFAULT_VALUE 64
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 16
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 16
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter MultTime INTEGER 5 ""
set_parameter_property MultTime DEFAULT_VALUE 5
set_parameter_property MultTime DISPLAY_NAME MultTime
set_parameter_property MultTime TYPE INTEGER
set_parameter_property MultTime UNITS None
set_parameter_property MultTime ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MultTime DESCRIPTION ""
set_parameter_property MultTime HDL_PARAMETER true
add_parameter AddTime INTEGER 9 ""
set_parameter_property AddTime DEFAULT_VALUE 9
set_parameter_property AddTime DISPLAY_NAME AddTime
set_parameter_property AddTime TYPE INTEGER
set_parameter_property AddTime UNITS None
set_parameter_property AddTime ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AddTime DESCRIPTION ""
set_parameter_property AddTime HDL_PARAMETER true
add_parameter InvSqrtTime INTEGER 17 ""
set_parameter_property InvSqrtTime DEFAULT_VALUE 17
set_parameter_property InvSqrtTime DISPLAY_NAME InvSqrtTime
set_parameter_property InvSqrtTime TYPE INTEGER
set_parameter_property InvSqrtTime UNITS None
set_parameter_property InvSqrtTime ALLOWED_RANGES -2147483648:2147483647
set_parameter_property InvSqrtTime DESCRIPTION ""
set_parameter_property InvSqrtTime HDL_PARAMETER true
add_parameter MinBodies INTEGER 21
set_parameter_property MinBodies DEFAULT_VALUE 21
set_parameter_property MinBodies DISPLAY_NAME MinBodies
set_parameter_property MinBodies TYPE INTEGER
set_parameter_property MinBodies UNITS None
set_parameter_property MinBodies ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MinBodies HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 2
set_interface_property avalon_slave_0 readWaitTime 2
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 addr address Input "((ADDR_WIDTH-1)) - (0) + 1"
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 writedata writedata Input "((EXT_DATA_WIDTH-1)) - (0) + 1"
add_interface_port avalon_slave_0 readdata readdata Output "((EXT_DATA_WIDTH-1)) - (0) + 1"
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock clock
set_interface_property vga associatedReset ""
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga VGA_B b Output 8
add_interface_port vga VGA_BLANK_n blank_n Output 1
add_interface_port vga VGA_CLK clk Output 1
add_interface_port vga VGA_G g Output 8
add_interface_port vga VGA_HS hs Output 1
add_interface_port vga VGA_R r Output 8
add_interface_port vga VGA_SYNC_n sync_n Output 1
add_interface_port vga VGA_VS vs Output 1

